language: ruby
rvm:
  - 2.1.0
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database scirate_test;' -U postgres
